### ISSUE TITLE
This is a very stripped-down bot, but it doesn't seem to work anymore

### ISSUE THREAD

**Issue by aTenb** [sanjithacks/Livegram-Bot-in-php-feedback-bot-telegram#1]
hello！"reply_to_message" does not contain "forward_from". When replying, the user ID can no longer be obtained. How to fix it?

**Comment by sanjithacks** [comment]
If user has not set forwarded message to everybody, for privacy reason message won't link to user account, hence we can't get user_id and can't reply them back.

**Comment by aTenb** [comment]
yes, @LivegramBot may work well using a database or a more complex method. In order to satisfy personal use, I had no choice but to see if there are any other clever ways to complete this function.

**Comment by sanjithacks** [comment]
You can store message id with user id, and then query message id to get
user_id from reply.  Message will be delivered if user hasn't blocked bot.
